config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "offers#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :profiles, only: [:show, :new, :create, :edit, :update]

  resources :users, only: %i[show] do
    resources :appointments, only: %i[index]
  end

  resources :offers, only: %i[index new create show destroy edit update] do
    resources :appointments, only: %i[new create destroy update edit]
  end
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :appointments
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description_and_location_and_category,
  using: { tsearch: { prefix: true } }

  validates :title, :description, :hourly_rate, :location, :photo, :category, presence: true
  validates :category, inclusion: { in: %w[Home Sports Education Pets Arts Music Garden Other] }
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :profile
  has_many :offers
  has_many :appointments
  #has_one_attached :photo

  validates :email, :password, presence: true
  validates :email, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @appointment = Appointment.new
    @offer = Offer.find(params[:offer_id])
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @appointment = Appointment.new(appointment_params)
    @appointment.user = current_user
    @appointment.offer = @offer

    if @appointment.save
      redirect_to user_path(current_user), notice: "Appointment was successfully booked."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @appointment = Appointment.find(params[:id])
    @offer = Offer.find(params[:offer_id])
  end

  def update
    @offer = Offer.find(params[:offer_id])
    @appointment = Appointment.find(params[:id])
    @appointment.offer = @offer

    @appointment.accepted = true
    @appointment.save!
    redirect_to user_appointments_path(current_user)
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to user_appointments_path(current_user), status: :see_other
  end

  def index
    @appointments = Appointment.where(user_id: current_user.id)
  end

  private

  def appointment_params
    params.require(:appointment).permit(:start_date, :end_date, :hours)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @offers = Offer.all
    # The `geocoded` scope filters only offers with coordinates
    @markers = @offers.geocoded.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude
      }
    end

    if params[:query].present?
      @offers = @offers.where("title ILIKE ?", "%#{params[:query]}%")
    end

    if params[:category].present?
      @offers = @offers.where("category ILIKE ?", "%#{params[:category]}%")
    end
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
      if @offer.save
        redirect_to @offer, notice: "Offer was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
  end

  def show
    @offer = Offer.find(params[:id])
    @markers = Array(@offer).map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude,
        info_window: render_to_string(partial: "info_window", locals: {offer: offer})
      }
    end
  end

  def edit
    @offer = Offer.find(params[:id])
    @user = current_user
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(offer_params)
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to offers_path, notice: "Offer was successfully deleted."
  end

  private
  def offer_params
    params.require(:offer).permit(:title, :description, :hourly_rate, :location, :latitude, :longitude, :address, :photo, :category)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def index
    @user = current_user
    @users = User.all
 end

 def dashboard
    @user = current_user
 end

 def profile
    @user = current_user
 end

 def settings
    @user = current_user
 end

 def edit_user
    @user = current_user
 end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController


  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      redirect_to @profile, notice: "Profile was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)
    redirect_to @profile, notice: "Profile was successfully updated."
  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy
    redirect_to root_path, notice: "Profile was successfully deleted."
  end

  private
  def profile_params
    params.require(:profile).permit(:name, :email, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    current_user = User.find(params[:id])
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.user = current_user
      if @user.save
        redirect_to @user, notice: "User was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_form.html.erb
<div class = "form-book">
  <%= simple_form_for [@offer, @appointment] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :hours %>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/appointments/index.html.erb
<% @disable_nav=true %>

<div class="appo-wrapper">
 <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Owner</th>
      <th scope="col">Title</th>
      <th scope="col">Start Date</th>
      <th scope="col">End Date</th>
      <th scope="col">Hours</th>
      <th scope="col">Accept</th>
      <th scope="col">Decline</th>
      <th scope="col">Accepted</th>
    </tr>
  </thead>
  <tbody>
   <% count = 1 %>
      <% current_user.appointments.each do |appointment| %>
        <tr>
          <td> <%= count %> </td>
            <% count += 1 %>
          <td> <%=appointment.offer.user.email %> </td>
          <td> <%=appointment.offer.title %> </td>
          <td> <%=appointment.start_date %> </td>
          <td> <%=appointment.end_date %> </td>
          <td> <%=appointment.hours %> </td>
          <td> <%= button_to "Accept offer", offer_appointment_path(appointment.offer, appointment), method: :put, class: "btn btn-success" %></td>
          <td> <%= link_to "Decline offer", offer_appointment_path(appointment.offer, appointment), method: :delete,  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger text-light" %></td>
          <% if appointment.accepted == true %>
                <td> Yes </td>
                <% else %>
                <td> No </td>
                <% end %>
        </tr>
      <% end %>
  </tbody>
 </table>
</div>
   <div class="back-offer-btn-wrapper">
    <%= link_to "Back to dashboard", user_path(current_user), class:"back-btn" %>
  </div>

app/views/appointments/new.html.erb
<% @disable_nav=true %>

<div class="form-wrapper-book">
  <div class="form-container-book">
    <div class="form-title-book">
      <p style="color: #fff; font-size:3rem;">Book an<span style="color: #4975CB;"> appointment</span></p>
       <h5 style="color: #fff; text-align: center;">Please fill out the form below to
       make and appointment</h5>
    </div>
    <%= render "form", Appointment: @appointment %>
 </div>
<div class="back-btn-wrapper">
  <%= link_to "Back to dashboard", current_user, class:"back-btn" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <title>Helpingly</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' unless @disable_nav %>
    <%= render 'shared/navbar_big' unless @disable_nav_big %>
      <%= yield %>
    <%= render 'shared/footer' unless @disable_footer %>
  </body>
</html>

app/views/offers/_calendar.html.erb
<label for="start">Start date:</label>

<input type="date" id="start" name="trip-start"
       value="2018-07-22"
       min="2018-01-01" max="2018-12-31">

app/views/offers/_form.html.erb
<div class="form-offer">
     <%= simple_form_for(@offer) do |f| %>
       <%= f.input :title %>
       <%= f.input :description %>
       <%= f.input :hourly_rate %>
       <%= f.input :location %>
       <%= f.input :category, collection: %w[Home Sports Education Pets Arts Music Garden Other] %>
       <%= f.input :address,
       input_html: {data: {address_autocomplete_target: "address"}},
       wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
       %>
       <%= f.input :photo, as: :file %>

         <div class="form-actions">
           <%= f.button :submit, 'Create' %>
         </div>
     <% end %>
  </div>

app/views/offers/_info_window.html.erb
<h2><%= offer.title %></h2>
<p><%= offer.address %></p>

app/views/offers/_user.html.erb
<div id="<%= dom_id offer %>">
  <p>
    <strong>Title:</strong>
    <%= user.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= user.description %>
  </p>
</div>

app/views/offers/edit.html.erb
<% @disable_nav=true %>

<div class="form-wrapper-edit-offer">
  <div class="form-container-edit-offer">
    <div class="form-title-edit-offer">
      <h1 style="color: #fff;">Edit <span style="color: #4975CB;"><%= @offer.title %></span></h1>
      <h5 style="color: #fff;">Give the customers what they needs.</h5>
    </div>
  <%= render "form", Offer: @offer %>
  </div>
  <div class="back-offer-btn-wrapper">
    <%= link_to "Back to dashboard", user_path(current_user), class:"back-btn" %>
  </div>
</div>

app/views/offers/index.html.erb
<% @disable_nav_big=true %>

<% @offers.each do |offer| %>
  <div class="carrusel-wrapper">
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
              <%= link_to cl_image_tag(offer.photo.key, id: "banner"), offer_path(offer) %>
            <div class="carru-title">
              <p> <%= offer.title %> </p>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
  </div>
<% end %>

<div class="new-search">
  <form action="/offers" method="get">
    <input type="text" name="query" placeholder="Find some offers" class="inp-1">
    <input type="submit" value="Search" class="inp-2">
  </form>
</div>

<div class="icon-category-wrapper">
    <div class="home icon-cat">
      <%= link_to request.params.merge(category: "Home") do %>
        <i class="fa-solid fa-house"></i>
      <% end %>
    </div>

    <div class="sports icon-cat">
      <%= link_to request.params.merge(category: "Sports") do %>
        <i class="fa-solid fa-basketball"></i>
      <% end %>
    </div>

    <div class="pets icon-cat">
      <%= link_to request.params.merge(category: "Pets") do %>
        <i class="fa-solid fa-dog"></i>
      <% end %>
    </div>
    <div class="education icon-cat">
      <%= link_to request.params.merge(category: "Education") do %>
        <i class="fa-solid fa-book"></i>
      <% end %>
    </div>
    <div class="music icon-cat">
      <%= link_to request.params.merge(category: "Music") do %>
        <i class="fa-solid fa-music"></i>
      <% end %>
    </div>
    <div class="art icon-cat">
      <%= link_to request.params.merge(category: "Arts") do %>
        <i class="fa-solid fa-paintbrush"></i>
       <% end %>
    </div>
    <div class="garden icon-cat">
      <%= link_to request.params.merge(category: "Garden") do %>
        <i class="fa-solid fa-tree"></i>
      <% end %>
    </div>
    <div class="other icon-cat">
      <%= link_to request.params.merge(category: "Other") do %>
        <i class="fa-solid fa-question"></i>
      <% end %>
    </div>
</div>

  <h3 class="offers-text" style="font-size: 2rem;">CHOOSE INTERESANT OFFERS IN <span style="color: #4975CB;">YOUR CITY</span></h3>
   <h5>Collect your favorite offers and save them.</h5>
  <div class="cards-wrapper">
    <% @offers.each do |offer| %>
      <div class="cards-cont">
        <%= link_to(offer_path(offer), class: "card-link") do %>
          <div class="card-ui">
            <% if offer.photo.attached? %>
             <div class="inner-text"><%= cl_image_tag offer.photo.key, height: 508, width: 753, crop: :fill, class:"img-home-offers"  %>
               <div class="cont-card-details">
                    <p><%= offer.title %></p>
                    <i class="fa-solid fa-circle-arrow-right fa-2x" style="color: #FB9638"></i>
               </div>
             </div>
            <% end %>
            <!--<div class="card-trip-infos">
              <div>
                <h2> <%#= offer.title  %> </h2>
                <p><%#= offer.description.truncate(30, separator: ' ') %> </p>
              </div>
              <h2 class="card-trip-pricing"> CHF <%#= offer.hourly_rate  %> </h2>
            </div>-->
          </div>
        <% end %>
      </div>
    <%end%>
  </div>
 <div>

app/views/offers/new.html.erb
<% @disable_nav=true %>

<div class="form-wrapper-offer">
  <div class="form-container-offer">
    <div class="form-title-offer">
      <h2 style="color: #fff;">Create your<span style="color: #4975CB;"> Offer</span></h2>
      <h5 style="color: #fff;">Lorem ipsum dolor sit amet,
       consectetur  impro</h5>
    </div>
    <%= render "form", Offer: @offer %>
  </div>
   <div class="back-offer-btn-wrapper">
     <%= link_to "Back to dashboard", user_path(current_user), class:"back-btn" %>
   </div>
</div>

app/views/offers/show.html.erb
<% @disable_nav=true %>

<div class="content-wrapper">
  <div class="offer-details">

      <div class="offer-imagen">
          <%= cl_image_tag(@offer.photo.key, width: 600, height: 840, crop: :fill) %>
      </div>

      <div class="offers-text-details">
        <div class="offer-d">
          <p>
            <%= @offer.title %>
          </p>
          <h4>
            <%= @offer.description %>
          </h4>

           <div class="mapita">
             <div id="cool-map" style="width: 75%; height: 400px;"
               data-controller="map"
               data-map-markers-value="<%= Array(@markers).to_json %>"
               data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
             </div>
           </div>
        </div>

        <div class="price-location">
          <h4><i class="fa-solid fa-location-dot" style="color: #4975CB;"></i> <%= @offer.location %></h2>
          <p>CHF <%= @offer.hourly_rate %></p>
        </div>
        <div class="booking">
          <%= link_to "Book", new_offer_appointment_path(@offer), class:"booking-btn" %>
        </div>
      </div>

  </div>
</div>

  <div class="more">
    <h2>Discover more from this people</h2>
    <div class="line"></div>
  </div>

<div class="offer-big-wrapper">
  <% @offer.user.offers.excluding(@offer).each do |offer| %>
    <div class="offer-more-wrapper">
        <%= link_to(offer_path(offer), class: "card-link") do %>
          <div class="offer-more-detail">
            <% if offer.photo.attached? %>
              <%= cl_image_tag offer.photo.key, height: 200, width: 200, crop: :fill, class:"rounded-img" %>
            <% end %>
          </div>
        <% end %>
      </div>
  <% end %>
</div>

app/views/profiles/_form.html.erb
<div class="form-profile">
     <%= simple_form_for(@profile) do |f| %>
       <%= f.input :photo, as: :file %>

         <div class="form-actions">
           <%= f.button :submit, 'Create', link_to: 'profiles#index' %>
         </div>
     <% end %>
  </div>

app/views/profiles/_profile.html.erb
<div>
    <%= cl_image_tag(@profile.photo.key, height: 200, width: 200, crop: :fill) %>
</div>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/destroy.html.erb
<h1>Profiles#destroy</h1>
<p>Find me in app/views/profiles/destroy.html.erb</p>

app/views/profiles/edit.html.erb
<% @disable_nav = true %>

  <%= render "form", Profile: @profile %>

app/views/profiles/index.html.erb
<% @disable_nav = true %>

<h1>Profiles#index</h1>
<div data-bs-toggle="modal" data-bs-target="#exampleModal" style="display:flex; justify-content: center;">
  Change photo
  <%# @profiles.each do |profile| %>
    <%#= cl_image_tag(profile.photo.key, height: 50, width: 50, crop: :fill) %>
  <%# end %>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>Profiles#new</h1>
<p>Find me in app/views/profiles/new.html.erb</p>
<% @disable_nav=true %>

<div class="form-wrapper-offer">
  <div class="form-container-offer">
    <div class="form-title-offer">
      <h2 style="color: #fff;">Edit your<span style="color: #4975CB;"> Profile</span></h2>
      <h5 style="color: #fff;">Lorem ipsum dolor sit amet,
       consectetur  impro</h5>
    </div>
    <%= render "form", Profile: @profile %>
  </div>
   <div class="back-offer-btn-wrapper">
     <%= link_to "Back to dashboard", user_path(current_user), class:"back-btn" %>
   </div>
</div>

app/views/profiles/show.html.erb
<% @disable_nav = true %>

<%= render @profile %>

<div>
  <%= link_to "Edit this profile", edit_profile_path(@profile) %>
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>

app/views/shared/_card.html.erb
<div class="card-trip">
  <%= cl_image_tag offer.photo.key, height: 300, width: 400, crop: :fill %>
  <div class="card-trip-infos">
    <div>
      <h2> <%= offer.title  %> </h2>
      <p><%= offer.description  %> </p>
    </div>
      <h2 class="card-trip-pricing"><%= offer.hourly_rate  %> </h2>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/Yamil-Pedroso/" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.yamilwebdeveloper.com/" target="_blank"><i class="fas fa-globe"></i></a>
    <a href="https://www.linkedin.com/in/yamil-pedroso/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fas fa-heart heart-style"></i> at Helpingly
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div class="left-nav">
    <div class="g-logo">
      <h1>G</h1>
      <p>elpingly</p>
    </div>
    <div class="g-title-wrapper">
     <div class="g-title">
      <p style="font-size:20px;">Here you will find what you are looking for.</p>
      <h2 style="color: #fff; font-size:4.5rem;">
        Now It’s Easy To
        Find <span style="color: #4975CB;">Offers</span>
      </h2>
     </div>
    </div>
  </div>
  <div class="nav-wrapper">

    <div class="primary-navigation">
      <ul id="navi">
         <% if user_signed_in? %>
          <h4>Welcome <%= current_user.name %></h4>
         <% end %>
        <li class="dropdown">
            <ion-icon name="person-circle-outline"></ion-icon>

          <!--<a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          </a>-->
          <ul class="dropdown-menu">
           <div>
            <% if user_signed_in? %>
              <li><%= link_to "My dashboard", user_path(current_user), class: "dropdown-item" %></li>
              <!--<li><%#= link_to "Edit profile", edit_profile_path(current_user), class: "dropdown-item" %></li>-->
              <li><%= button_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete, form: {"data-turbo": false} %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %> </li>
              <li><%= link_to "Log in", new_user_session_path, class: "dropdown-item" %></li>
            <% end %>
           </div>
          </ul>
        </li>
        <!--<li><a href="#"> <ion-icon name="person-circle-outline"></ion-icon></a>
         <ul class="dropdown" style="z-index: 1;">
          <%# if user_signed_in? %>
            <li><%#= link_to "My page", user_path(current_user) %></li>
            <li><%#= link_to "Log out", destroy_user_session_path, method: :delete, form: {"data-turbo": false} %></li>
          <%# else %>
            <li><%#= link_to "Sign up", new_user_registration_path %> </li>
             <li><%#= link_to "Log in", new_user_session_path %></li>
          <%# end %>
       </ul>
      </li>-->
     </ul>
   </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@offer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <%= f.input :photo, as: :file %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_form_profile_pic.html.erb
<div class="form-user-profile">
     <%= simple_form_for(current_user) do |f| %>
       <%= f.input :name %>
       <%= f.input :photo, as: :file %>

         <div class="form-actions">
           <%= f.button :submit, 'Create' %>
         </div>
     <% end %>
  </div>

app/views/users/show.html.erb
<% @disable_nav=true %>

<div class="dashboard-wrapper">
   <div class="dash-right">
    <div class="title-co-wrapper">
          <!--<i class="fa fa-user"></i>-->
          <h2>Hello <%= current_user.name %></h2>
          <%= link_to "Create a new offer", new_offer_path, class:"c-offer" %>
    </div>
     <div class="card-collection-wrapper">
       <div class="cards-wrapper-dash">
         <% current_user.offers.each do |offer| %>
           <div class="cards-cont">
             <%= link_to(offer_path(offer), class: "card-link-dash") do %>
               <div class="card-ui-dash">
                 <%= cl_image_tag offer.photo.key, height: 200, width: 353, crop: :fill, class:"img-details" %>
                 <div class="card-info">
                   <div class="card-td">
                     <h2> <%= offer.title  %> </h2>
                     <p><%= offer.description.truncate(30, separator: ' ') %> </p>
                   </div>
                   <p class="card-price"> CHF <%= offer.hourly_rate  %> </p>
                 </div>
               </div>
                <div class="card-btn">
                   <%= link_to 'Delete', offer_path(offer), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'del-btn' %>
                   <%= link_to 'Edit', edit_offer_path(offer), class: "edit-btn" %>
                 </div>
             <% end %>
           </div>
         <%end%>
       </div>
    </div>

     <h2 class="overview-title"> Overview of my Bookings </h2>
     <div class="overview-wrapper">

       <table class="table">
         <thead>
           <tr>
             <th scope="col">Owner</th>
             <th scope="col">Title</th>
             <th scope="col">Start Date</th>
             <th scope="col">End Date</th>
             <th scope="col">Hours</th>
             <th scope="col">Accepted?</th>
           </tr>
         </thead>
         <tbody>
             <% current_user.appointments.each do |appointment| %>
               <tr>
                 <td> <%=appointment.offer.user.email %> </td>
                 <td> <%=appointment.offer.title %> </td>
                 <td> <%=appointment.start_date %> </td>
                 <td> <%=appointment.end_date %> </td>
                 <td> <%=appointment.hours %> </td>
                 <% if appointment.accepted == true %>
                 <td style="color: #475841"> Yes </td>
                 <% else %>
                 <td style="color: rgb(255, 0, 0)"> No </td>
                 <% end %>
               </tr>
             <% end %>
         </tbody>
       </table>
     </div>
       <div class="manage-appo">
         <%= link_to(user_appointments_path(current_user), class:"appo-btn") do %>
           Manage appointments <i class="fas fa-arrow-right"></i>
         <% end %>
       </div>
 </div>
</div>